blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    body = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/images', verbose_name='Изображение (превью)', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    views_count = models.PositiveIntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'image', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True) # при указывании False - выходят неопубликованные статьи
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">Удаление</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить статью "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ object.title }}</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">
                            {{ object.title }} ({{ object.slug }})
                        </h4>
                        <p class="card-text">
                            {{ object.body }}
                        </p>
                        <p class="font-italic">{{ object.created_at }}</p>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.views_count }}
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <img src="{{ object.image | media_filter }}">
                </div>
            </div>
        </div>
        <div class="col mb-5">
            <a class="btn btn-outline-secondary" href="{% url 'blog:list' %}" role="button">Назад</a>
        </div>

    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">
                {% if object %}
                Редактирование
                {% else %}
                Создание
                {% endif %}
            </h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                    Сохранить
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-12 mb-5">
        <a class="btn btn-outline-secondary" href="{% url 'blog:list' %}" role="button">Назад</a>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">Статьи</h1>
        </div>
    </div>
</section>
<div class="album py-3 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-3">
            {% if user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
            {% endif %}
        </div>
    </div>
</div>

<div class="album py-3 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}

            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Статья:
                            {{ object }}
                        </p>
                        <p class="card-text">Содержание:
                            {{ object.body|truncatechars:100 }}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-outline-info" href="{% url 'blog:view' object.pk %}"
                                   role="button">Просмотр</a>
                                {% if user.is_authenticated %}
                                <a class="btn btn-outline-info" href="{% url 'blog:update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-outline-info" href="{% url 'blog:delete' object.pk %}"
                                   role="button">Удалить</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}