blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (
    CategoryListView,
    CategoryDetailView,
    ProductDetailView,
    ContactsTemplateView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path("contacts/", ContactsTemplateView.as_view(), name="contacts"),
    path("", CategoryListView.as_view(), name="categories_list"),
    path("catalog/<int:pk>/", CategoryDetailView.as_view(), name="category_one"),
    path(
        "products/<int:pk>/",
        cache_page(60 * 60)(ProductDetailView.as_view()),
        name="products",
    ), # Кеширование на 1 час
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<int:pk>", ProductUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ProductDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Product(models.Model):

    # STATUS_CHOICES = (
    #     ("new", "Новый"),
    #     ("in_stock", "В наличии"),
    #     ("out_of_stock", "Нет в наличии"),
    # )

    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(
        upload_to="products/images", verbose_name="Изображение (превью)", **NULLABLE
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        verbose_name="Категория",
        related_name="products",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена за покупку"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    # is_published = models.CharField(verbose_name="Опубликовано", choices=STATUS_CHOICES)

    def __str__(self):
        return f"{self.name}, {self.description}, {self.price}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "price"]
        permissions = [
            ("can_edit_description", "Может менять описание продукта"),
            ("can_cancel_publishing", "Может отменять публикацию продукта"),
            ("can_change_category", "Может менять категорию продукта")
        ]


class Category(models.Model):

    name = models.CharField(max_length=100, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.name}, {self.description}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"



class Version(models.Model):

    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name="Версия",
        related_name="version_product",
    )

    number_version = models.CharField(default=0, verbose_name="Номер версии")
    name_version = models.CharField(max_length=100, verbose_name="Наименование версии")
    is_current = models.BooleanField(
        default=True, verbose_name="Признак текущей версии"
    )

    def __str__(self):
        return f"{self.number_version}, {self.name_version}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from django.forms import BooleanField, BaseInlineFormSet

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        prohibit_words = ['казино', 'криптовалюта', 'крипта',
                          'биржа', 'дешево', 'бесплатно', 'обман',
                          'полиция', 'радар',]
        if cleaned_name in prohibit_words:
            raise forms.ValidationError('В названии присутствуют запрещенные слова')
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data['description']
        prohibit_words = ['казино', 'криптовалюта', 'крипта',
                          'биржа', 'дешево', 'бесплатно', 'обман',
                          'полиция', 'радар',]
        if cleaned_description in prohibit_words:
            raise forms.ValidationError('В описании присутствуют запрещенные слова')
        return cleaned_description


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published',)


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from catalog.models import Category, Product, Version
from django.urls import reverse_lazy, reverse
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from django.forms import inlineformset_factory
from catalog.services import get_category_list_from_cache


class ContactsTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/category_list.html'

    def get_queryset(self):
        return get_category_list_from_cache()


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category

    def get_success_url(self):
        return reverse('catalog:category_one', args=[self.kwargs.get('pk')])


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_success_url(self):
        return reverse('catalog:category_one', args=[self.kwargs.get('pk')])


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:categories_list')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    #form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:category_one', args=[self.get_object().category.pk]) # kwargs={'pk': self.object.pk}

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        permission_required = ['catalog.can_edit_description',
                               'catalog.can_cancel_publishing',
                               'catalog.can_change_category',]
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        elif [user.has_perm(i for i in permission_required)]:
        # elif user.has_perm('catalog.can_edit_description') and user.has_perm('catalog.can_cancel_publishing') and user.has_perm('catalog.can_change_category'):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:categories_list')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="ru" data-bs-theme="auto">
<head>
    <script type="text/javascript"
            charset="UTF-8"></script>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
{% include 'catalog/includes/inc_main_menu.html' %}
</header>

<main>

{% block content %}
{% endblock %}


</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="mb-1">&copy; {% now 'Y' %}</p>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ object.name }}</h1>
            <p class="lead text-body-secondary">{{ object.description }}</p>
        </div>
    </div>
</section>

<div class="container">
    <div class="col-12 mb-5">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить товар</a>
        {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for category in object.products.all %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <img src="{{ category.image | media_filter }}">
                <div class="card-body">
                    <h4 class="card-title">{{ category.name }}</h4>
                    <p class="card-text">
                        {{ category.description }}
                    <h6 class="text">Цена: {{ category.price }} рублей.</h6>
                    </p>
                    <a class="btn btn-outline-primary" href="{% url 'catalog:products' category.pk %}" role="button">Подробнее</a>
                    {% if perms.catalog.can_edit_description and perms.catalog.can_cancel_publishing and perms.catalog.can_change_category or user == category.owner%}
                    <a class="btn btn-outline-success" href="{% url 'catalog:update' category.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-outline-danger" href="{% url 'catalog:delete' category.pk %}" role="button">Удалить</a>
                    {% endif %}
                </div>
                {% for version in category.version_product.all %}
                <div class="card-footer">Версия: {{ version.number_version }} / {{ version.name_version }}</div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <a class="btn btn-outline-secondary" href="{% url 'catalog:categories_list' %}" role="button">Назад в
            категории</a>
    </div>
</div>
    {% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">Категории</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <ul>
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for category in object_list %}
                    <div class="col-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body text-center">
                                <h4 class="card-title">{{ category.name }}</h4>
                                <p class="card-text" data-auto="snippet title">
                                    {{ category.description|truncatechars:100 }}
                                </p>
                                <a href="{% url 'catalog:category_one' category.pk %}" class="btn btn-link">Перейти</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
        </ul>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_main_page.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ title }}</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <ul>
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for category in category_list %}
                    <div class="col-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body text-center">
                                <h4 class="card-title">{{ category.name }}</h4>
                                <p class="card-text" data-auto="snippet title">
                                    {{ category.description|truncatechars:100 }}
                                </p>
                                <a href="{% url 'catalog:category_one' category.pk %}" class="btn btn-link">Перейти</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
        </ul>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/category_one.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ title }}</h1>
            <p class="lead text-body-secondary">{{ category_one.description }}</p>
        </div>
    </div>
</section>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for category in prod_cat %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <img src="{{ category.image | media_filter }}">
                <div class="card-body">
                    <h4 class="card-title">{{ category.name }}</h4>
                    <p class="card-text">
                        {{ category.description }}
                    <h6 class="text">Цена: {{ category.price }} рублей.</h6>
                    </p>
                    <a class="btn btn-primary" href="{% url 'catalog:products' category.pk %}" role="button">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <a style="text-align:center" href="{% url 'catalog:category_main_page' %}" role="button">Назад в категории</a>
    {% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ title }}</h1>
            <p class="lead text-body-secondary"></p>
        </div>
    </div>
</section>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-6 col-md-4 col-sm-6">
            <div class="card mb-2 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>77123456789</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Москва, улица Академика Королева, 77</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Введите сообщение" required></textarea>
                        </div>
                        <button type="button" class="btn btn-outline-primary mb-2">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">Удаление</h1>
        </div>
    </div>
</section>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить товар "{{ object.title }}"?</p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'catalog:categories_list' %}" class="btn btn-warning">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="font-weight-bold">{{ object.name }}</h1>
        </div>
    </div>
</section>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card">
                <img src="{{ object.image | media_filter }}">
                <div class="card-body">
                    <h4 class="card-title">{{ object.name }}</h4>
                    <p class="card-text">
                        {{ object.description }}
                    <h6 class="text">Цена: {{ object.price }} рублей.</h6>
                    </p>
                </div>
                {% for version in object.version_product.all %}
                <div class="card-footer">
                    Версия: {{ version.number_version }} / {{ version.name_version }}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div>
        <a class="btn btn-outline-secondary"  href="{% url 'catalog:category_one' object.category.pk %}" role="button">Назад к
            выбору продукта</a>
    </div>
</div>

{% endblock %}